# Generated by Django 4.1.7 on 2023-11-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('licenseNo', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
