# Generated by Django 4.1.7 on 2023-11-12 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusUser',
            fields=[
                ('bus_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=255)),
                ('ashesi_id', models.CharField(max_length=255, unique=True)),
                ('ashesi_email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_name', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(default=None, max_length=1, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='licenseNo',
            new_name='license_no',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.CreateModel(
            name='TripTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_started', models.DateTimeField(auto_now_add=True)),
                ('has_started', models.BooleanField(default=False)),
                ('has_ended', models.BooleanField(default=False)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='abs_app.driver')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_taken', to='abs_app.trip')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='abs_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop', to='abs_app.stop')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='abs_app.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date_time', models.DateTimeField()),
                ('bus_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busUser', to='abs_app.bususer')),
            ],
        ),
    ]
