# Generated by Django 4.1.7 on 2023-11-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusUser',
            fields=[
                ('bus_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default=None, max_length=255)),
                ('lname', models.CharField(default=None, max_length=255)),
                ('passwd', models.CharField(default=None, max_length=255)),
                ('ashesi_id', models.CharField(max_length=255, unique=True)),
                ('ashesi_email', models.EmailField(default=None, max_length=255, unique=True)),
                ('momo_no', models.CharField(default=None, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_ashesi_id', models.CharField(default=None, max_length=255, unique=True)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_name', models.TextField(default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(default=None, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_no', models.CharField(default=None, max_length=255, unique=True)),
                ('color', models.CharField(default=None, max_length=255)),
                ('model', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TripTaken',
            fields=[
                ('trip_taken_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('date_time_started', models.DateTimeField(auto_now_add=True)),
                ('date_time_ended', models.DateTimeField(null=True)),
                ('has_started', models.BooleanField(default=True)),
                ('has_ended', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_taken', to='abs_app.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_taken', to='abs_app.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_taken', to='abs_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('trip_stop_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stop', to='abs_app.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stop', to='abs_app.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('ref', models.CharField(default=None, max_length=255)),
                ('payment_date_time', models.DateTimeField()),
                ('bus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='abs_app.bususer')),
                ('trip_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='abs_app.triptaken')),
            ],
        ),
    ]
