# Generated by Django 4.1.7 on 2023-11-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_time',
            field=models.TimeField(default=None),
        ),
    ]
