# Generated by Django 4.1.7 on 2023-11-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0002_trip_trip_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
