# Generated by Django 4.1.7 on 2023-11-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0003_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip_time',
            new_name='trip_end_time',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_start_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
