# Generated by Django 4.1.7 on 2023-11-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0004_rename_trip_time_trip_trip_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_name',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
