# Generated by Django 4.1.7 on 2023-11-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0005_alter_trip_trip_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.AlterField(
            model_name='triptaken',
            name='date_time_ended',
            field=models.DateTimeField(default=None),
        ),
    ]
