# Generated by Django 4.1.7 on 2023-11-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0006_remove_vehicle_color_alter_triptaken_date_time_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triptaken',
            name='date_time_ended',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
