# Generated by Django 4.1.7 on 2023-11-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0007_alter_triptaken_date_time_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
        ),
    ]
