# Generated by Django 4.1.7 on 2023-12-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0008_stop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
