# Generated by Django 4.1.7 on 2023-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0009_driver_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
