# Generated by Django 4.1.7 on 2023-12-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0010_alter_payment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
