# Generated by Django 4.1.7 on 2023-12-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0011_alter_payment_payment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='payment', to='abs_app.stop'),
        ),
    ]
