# Generated by Django 4.1.7 on 2023-12-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0012_payment_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('parking_space_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('parking_space_name', models.CharField(default=None, max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_space', to='abs_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DriversLicense',
            fields=[
                ('license_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=255, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abs_app.driver')),
            ],
        ),
    ]
