# Generated by Django 4.1.7 on 2023-12-06 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0013_vehicle_is_available_parkingspace_driverslicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='time_parked',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
