# Generated by Django 4.1.7 on 2023-12-06 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0015_alter_parkingspace_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='time_parked',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='parking_space', to='abs_app.vehicle'),
        ),
    ]
