# Generated by Django 4.1.7 on 2023-12-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0017_alter_parkingspace_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='time_parked',
        ),
    ]
